# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getTextLevel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MasterFreqEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MasterFreqEdit.setGeometry(QtCore.QRect(170, 250, 113, 20))
        self.MasterFreqEdit.setObjectName("MasterFreqEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 200, 113, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.MasterFreqLabel = QtWidgets.QLabel(self.centralwidget)
        self.MasterFreqLabel.setGeometry(QtCore.QRect(80, 180, 111, 16))
        self.MasterFreqLabel.setObjectName("MasterFreqLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 390, 111, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(570, 80, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(440, 80, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.MasterFreqLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.MasterFreqLabel_2.setGeometry(QtCore.QRect(520, 80, 41, 16))
        self.MasterFreqLabel_2.setObjectName("MasterFreqLabel_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 410, 111, 16))
        self.label_4.setObjectName("label_4")
        self.MasterFreqEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.MasterFreqEdit_2.setGeometry(QtCore.QRect(150, 410, 113, 20))
        self.MasterFreqEdit_2.setObjectName("MasterFreqEdit_2")
        self.MasterFreqEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.MasterFreqEdit_3.setGeometry(QtCore.QRect(150, 430, 113, 20))
        self.MasterFreqEdit_3.setText("")
        self.MasterFreqEdit_3.setObjectName("MasterFreqEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 430, 91, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setObjectName("actionProperties")
        self.menuFile.addAction(self.actionProperties)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MasterFreqLabel.setText(_translate("MainWindow", "Master Frequency List"))
        self.label_2.setText(_translate("MainWindow", "Known Morph DBs"))
        self.label_3.setText(_translate("MainWindow", "Create Anki Deck"))
        self.pushButton.setText(_translate("MainWindow", "..."))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.MasterFreqLabel_2.setText(_translate("MainWindow", "Target"))
        self.label_4.setText(_translate("MainWindow", "Super Deck Name"))
        self.label_5.setText(_translate("MainWindow", "Super Deck Name"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))


