# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manabi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MasterFreqLabel = QtWidgets.QLabel(self.centralwidget)
        self.MasterFreqLabel.setGeometry(QtCore.QRect(80, 180, 111, 16))
        self.MasterFreqLabel.setObjectName("MasterFreqLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 390, 111, 16))
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(570, 80, 62, 22))
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setProperty("value", 98.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(440, 80, 62, 22))
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.MasterFreqLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.MasterFreqLabel_2.setGeometry(QtCore.QRect(520, 80, 41, 16))
        self.MasterFreqLabel_2.setObjectName("MasterFreqLabel_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 410, 111, 16))
        self.label_4.setObjectName("label_4")
        self.MasterFreqEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.MasterFreqEdit_2.setGeometry(QtCore.QRect(150, 410, 113, 20))
        self.MasterFreqEdit_2.setObjectName("MasterFreqEdit_2")
        self.MasterFreqEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.MasterFreqEdit_3.setGeometry(QtCore.QRect(150, 430, 113, 20))
        self.MasterFreqEdit_3.setText("")
        self.MasterFreqEdit_3.setObjectName("MasterFreqEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 430, 91, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(320, 370, 131, 41))
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(420, 160, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 250, 216, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.MasterFreqEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.MasterFreqEdit.setObjectName("MasterFreqEdit")
        self.horizontalLayout_2.addWidget(self.MasterFreqEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(91, 201, 216, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.masterFreqButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.masterFreqButton.setObjectName("masterFreqButton")
        self.horizontalLayout.addWidget(self.masterFreqButton)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.minimize_to_tray = QtWidgets.QCheckBox(self.centralwidget)
        self.minimize_to_tray.setEnabled(True)
        self.minimize_to_tray.setGeometry(QtCore.QRect(640, 540, 101, 17))
        self.minimize_to_tray.setChecked(True)
        self.minimize_to_tray.setObjectName("minimize_to_tray")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setShortcut("")
        self.actionProperties.setObjectName("actionProperties")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.actionEdit_properties = QtWidgets.QAction(MainWindow)
        self.actionEdit_properties.setObjectName("actionEdit_properties")
        self.menuFile.addAction(self.actionProperties)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDonate)
        self.menuTool.addAction(self.actionEdit_properties)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setProperty("closeEvent", _translate("MainWindow", "ds"))
        self.MasterFreqLabel.setText(_translate("MainWindow", "Master Frequency List"))
        self.label_2.setText(_translate("MainWindow", "Known Morph DBs"))
        self.label_3.setText(_translate("MainWindow", "Create Anki Deck"))
        self.MasterFreqLabel_2.setText(_translate("MainWindow", "Target"))
        self.label_4.setText(_translate("MainWindow", "Super Deck Name"))
        self.label_5.setText(_translate("MainWindow", "Super Deck Name"))
        self.label.setText(_translate("MainWindow", "Morphemizer"))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.masterFreqButton.setText(_translate("MainWindow", "..."))
        self.minimize_to_tray.setText(_translate("MainWindow", "minimize to tray"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTool.setTitle(_translate("MainWindow", "Tools"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.actionEdit_properties.setText(_translate("MainWindow", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
