# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 498)
        self.dbAPath = QtWidgets.QLineEdit(Dialog)
        self.dbAPath.setGeometry(QtCore.QRect(40, 40, 113, 20))
        self.dbAPath.setObjectName("dbAPath")
        self.dbBPath = QtWidgets.QLineEdit(Dialog)
        self.dbBPath.setGeometry(QtCore.QRect(40, 70, 113, 20))
        self.dbBPath.setObjectName("dbBPath")
        self.AFileButton = QtWidgets.QToolButton(Dialog)
        self.AFileButton.setGeometry(QtCore.QRect(10, 40, 25, 19))
        self.AFileButton.setObjectName("AFileButton")
        self.BFileButton = QtWidgets.QToolButton(Dialog)
        self.BFileButton.setGeometry(QtCore.QRect(10, 70, 25, 19))
        self.BFileButton.setObjectName("BFileButton")
        self.showA = QtWidgets.QPushButton(Dialog)
        self.showA.setGeometry(QtCore.QRect(11, 126, 31, 23))
        self.showA.setObjectName("showA")
        self.showB = QtWidgets.QPushButton(Dialog)
        self.showB.setEnabled(True)
        self.showB.setGeometry(QtCore.QRect(50, 130, 31, 23))
        self.showB.setObjectName("showB")
        self.ADiffB = QtWidgets.QPushButton(Dialog)
        self.ADiffB.setGeometry(QtCore.QRect(11, 160, 75, 23))
        self.ADiffB.setObjectName("ADiffB")
        self.BDiffA = QtWidgets.QPushButton(Dialog)
        self.BDiffA.setGeometry(QtCore.QRect(11, 194, 75, 23))
        self.BDiffA.setObjectName("BDiffA")
        self.symmetricDiff = QtWidgets.QPushButton(Dialog)
        self.symmetricDiff.setGeometry(QtCore.QRect(11, 228, 77, 23))
        self.symmetricDiff.setObjectName("symmetricDiff")
        self.ABUnion = QtWidgets.QPushButton(Dialog)
        self.ABUnion.setGeometry(QtCore.QRect(11, 262, 75, 23))
        self.ABUnion.setObjectName("ABUnion")
        self.ABIntersection = QtWidgets.QPushButton(Dialog)
        self.ABIntersection.setGeometry(QtCore.QRect(11, 296, 75, 23))
        self.ABIntersection.setObjectName("ABIntersection")
        self.morphemizerBox = QtWidgets.QComboBox(Dialog)
        self.morphemizerBox.setGeometry(QtCore.QRect(10, 340, 69, 22))
        self.morphemizerBox.setObjectName("morphemizerBox")
        self.extractMorphemes = QtWidgets.QPushButton(Dialog)
        self.extractMorphemes.setGeometry(QtCore.QRect(10, 380, 151, 23))
        self.extractMorphemes.setObjectName("extractMorphemes")
        self.saveResults = QtWidgets.QPushButton(Dialog)
        self.saveResults.setGeometry(QtCore.QRect(10, 410, 141, 23))
        self.saveResults.setObjectName("saveResults")
        self.langBox = QtWidgets.QComboBox(Dialog)
        self.langBox.setGeometry(QtCore.QRect(10, 470, 69, 22))
        self.langBox.setObjectName("langBox")
        self.fullInfo = QtWidgets.QRadioButton(Dialog)
        self.fullInfo.setGeometry(QtCore.QRect(20, 440, 82, 17))
        self.fullInfo.setChecked(True)
        self.fullInfo.setObjectName("fullInfo")
        self.onlyMorphs = QtWidgets.QRadioButton(Dialog)
        self.onlyMorphs.setGeometry(QtCore.QRect(90, 440, 82, 17))
        self.onlyMorphs.setObjectName("onlyMorphs")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 40, 251, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.summaryLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.summaryLabel.sizePolicy().hasHeightForWidth())
        self.summaryLabel.setSizePolicy(sizePolicy)
        self.summaryLabel.setText("")
        self.summaryLabel.setObjectName("summaryLabel")
        self.verticalLayout.addWidget(self.summaryLabel)
        self.posTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(47)
        sizePolicy.setVerticalStretch(103)
        sizePolicy.setHeightForWidth(self.posTable.sizePolicy().hasHeightForWidth())
        self.posTable.setSizePolicy(sizePolicy)
        self.posTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.posTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.posTable.setObjectName("posTable")
        self.posTable.setColumnCount(0)
        self.posTable.setRowCount(0)
        self.posTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.posTable)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 60, 431, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(0)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dbTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(206)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dbTable.sizePolicy().hasHeightForWidth())
        self.dbTable.setSizePolicy(sizePolicy)
        self.dbTable.setMidLineWidth(0)
        self.dbTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dbTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dbTable.setDragDropOverwriteMode(False)
        self.dbTable.setAlternatingRowColors(False)
        self.dbTable.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dbTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.dbTable.setShowGrid(True)
        self.dbTable.setCornerButtonEnabled(True)
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(0)
        self.dbTable.setRowCount(0)
        self.dbTable.horizontalHeader().setCascadingSectionResizes(True)
        self.dbTable.horizontalHeader().setDefaultSectionSize(50)
        self.dbTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.dbTable)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dbAPath.setPlaceholderText(_translate("Dialog", "database A path"))
        self.dbBPath.setPlaceholderText(_translate("Dialog", "database B path"))
        self.AFileButton.setText(_translate("Dialog", "..."))
        self.BFileButton.setText(_translate("Dialog", "..."))
        self.showA.setText(_translate("Dialog", "A"))
        self.showB.setText(_translate("Dialog", "B"))
        self.ADiffB.setText(_translate("Dialog", "A Diff B"))
        self.BDiffA.setText(_translate("Dialog", "B Diff A"))
        self.symmetricDiff.setText(_translate("Dialog", "Symmetric Diff"))
        self.ABUnion.setText(_translate("Dialog", "Union"))
        self.ABIntersection.setText(_translate("Dialog", "Intersection"))
        self.extractMorphemes.setText(_translate("Dialog", "Extract morphemes from file"))
        self.saveResults.setText(_translate("Dialog", "Save results to db"))
        self.fullInfo.setText(_translate("Dialog", "Full Info"))
        self.onlyMorphs.setText(_translate("Dialog", "Only Morphs"))
        self.label.setText(_translate("Dialog", "Summary"))
        self.label_2.setText(_translate("Dialog", "Database Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
